name: Pull Request Trigger

on:
  pull_request_target:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push to webhook
        run: |
          echo $AUTHOR $TITLE $LINK 
          curl "$WEBHOOK" -X POST -H "Authorization: $AUTH_TOKEN" -d "$AUTHOR"$'\n'"$TITLE"$'\n'"$LINK"
        env:
          AUTHOR: ${{ github.event.pull_request.user.login }}
          TITLE: ${{ github.event.pull_request.title }}
          LINK: ${{ github.event.pull_request.url }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          WEBHOOK: ${{ secrets.WEBHOOK_URL }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          

        
